name: Build documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

env:
  UV_SYSTEM_PYTHON: 1
  UV_TORCH_BACKEND: auto

jobs:
  build_documentation:
    runs-on: ubuntu-22.04
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      PR_NUMBER: ${{ github.event.number }}
      EVENT_CONTEXT: ${{ toJSON(github.event) }}
      PR_CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}

    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7
        with:
          node-version: "20"
          cache-dependency-path: "kit/package-lock.json"

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"

      - name: Set environment variables
        run: |
          cd optimum
          version=`echo "$(grep '^__version__ =' intel/version.py | cut -d '=' -f 2 | xargs)"`

          if [[ $version == *.dev0 ]]
          then
            echo "VERSION=main" >> $GITHUB_ENV
          else
            echo "VERSION=v$version" >> $GITHUB_ENV
          fi

          cd ..

      - name: Setup environment
        run: |
          pip install --upgrade pip uv
          uv pip install git+https://github.com/huggingface/doc-builder
          uv pip install . --no-deps
          doc-builder light-install optimum.intel

      - name: Make documentation
        shell: bash
        run: |
          make doc BUILD_DIR=./build_dir VERSION=${{ env.VERSION }}
          cd build_dir
          mv ./optimum.intel ./optimum-intel
          cd ..

      - name: Sync to bucket
        env:
          HF_TOKEN: ${{ secrets.HF_DOC_BUILD_PUSH }}
        run: |
          cd build_dir
          uvx --from huggingface_hub hf sync ./optimum-intel hf://buckets/hf-doc-build/doc/optimum-intel
          cd ..

      - name: Push to dataset (legacy)
        env:
          HF_TOKEN: ${{ secrets.HF_DOC_BUILD_PUSH }}
          COMMIT_MSG: "Updated with commit ${{ env.COMMIT_SHA }} See: https://github.com/huggingface/optimum-intel/commit/${{ env.COMMIT_SHA }}"
        run: |
          cd build_dir
          doc-builder push optimum-intel \
            --doc_build_repo_id "hf-doc-build/doc-build" \
            --commit_msg "${COMMIT_MSG}" \
            --n_retries 5
          cd ..