name: Legacy Remote Code Models Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - v*-release
  pull_request:
    branches:
      - main
      - v*-release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  UV_TORCH_BACKEND: cpu
  UV_SYSTEM_PYTHON: true
  TRANSFORMERS_IS_CI: true
  HF_TOKEN: ${{ secrets.HF_HUB_READ_TOKEN }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        test-pattern:
          [
            "*decoder*",
            "*seq2seq*",
          ]

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip uv
          uv pip install .[tests] librosa diffusers

      - name: Login with fork PRs CI token
        if: ${{ env.HF_TOKEN == '' }}
        run: |
          python tests/scripts/login_with_ci_token.py

      - name: Legacy remote-code models validation
        run: |
          uv pip install "transformers==4.51.0" transformers_stream_generator
          pytest tests/openvino/${{ matrix.test-pattern }} -k "(chatglm and not chatglm4) or (minicpm and not minicpmv) or (qwen and not qwen2 and not qwen3 and not videochat_flash_qwen) or arctic or deepseek or llava-qwen2 or phi3_v or phi4mm or minicpmo or test_filtered_architectures" --durations=0
