name: OpenVINO - Examples Test

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 1  # run weekly: every Monday at 1am
  push:
    paths:
    - '.github/workflows/test_openvino_examples.yml'
    - 'examples/openvino/**'
  pull_request:
    paths:
    - '.github/workflows/test_openvino_examples.yml'
    - 'examples/openvino/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.11"]

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install .[openvino] jstyleson pytest
        pip install -r examples/openvino/audio-classification/requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
        pip install -r examples/openvino/image-classification/requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
        pip install -r examples/openvino/question-answering/requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
        pip install -r examples/openvino/text-classification/requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

    - name: Test examples
      run: |
        python -m pytest examples/openvino/test_examples.py
